=== comahax/oldsnippet/PBOSS-REWARD/src/com/sunrise/boss/resource/excelout/excelout.dtd
<?xml version='1.0' encoding='UTF-8' ?>
<!--
************************************************************
该dtd文件用于说明excelout.xml文件的配置方式

excelout-config为文档元素,含有最少一个entity子元素
************************************************************
-->
<!ELEMENT excelout-config (entity+)>

<!--
***********************************************************
 entity元素指定一个要导出数据的VO(对于多表查询的时候,因为有多个VO,所以
 需要使用复杂查询的方式,建立一个虚拟VO).
 entity元素的name属性是必须的,name的值应为VO的全类名,以保持唯一;entiy元素含有
 delegate,formname,resbundle,outfilename,fields子元素,
 除了delegate元素外,其它的子元素必须要依声明的顺序存在.
***********************************************************
-->
<!ELEMENT entity (delegate*,formname,resbundle,outfilename,fields)>
<!ATTLIST entity name CDATA #REQUIRED>

<!--
***********************************************************
 delegate元素指定调用其方法获得查询数据及其记录数的代理类,该元素不是必需
 的,如果在excelout.xml文件没有指定,则程序中会使用
 "com.sunrise.boss.delegate.common.CommonDelegate"作为元素内容;
 
 delegate元素含有query,count两属性,query属性指定delegate类中用以获得
 查询数据的查询方法的名称,如果没有指定该属性的值程序中默认使用"doQuery"作为方法名;
 count属性指定delegate类中用以获得符合导出条件的 记录总数的方法名称,
 如果没有指定该属性的值,程序中默认使用"doCount"作为方法名.
***********************************************************
-->
<!ELEMENT delegate (#PCDATA)>
<!ATTLIST delegate 
	query CDATA #IMPLIED
	count CDATA #IMPLIED
>

<!--
***********************************************************
 元素formname指定进行查询操作的action对应的form类的全类名.
 该元素是必需的
***********************************************************
-->
<!ELEMENT formname (#PCDATA)>

<!--
***********************************************************
 元素resbundle指定查询页面上显示的中文字段标题所对应的资源文件
  元素的内容为在resmanage-struts-config.xml文件中声明的message-resources
  元素的属性key的值;
  
 path属性指定资源文件的路径名.
 
 注意:页面上中文标题使用<bean:message bundle="key" key="fieldName"/>的方式
 即资源文件中,中文标题内容对应的key应与vo对应的字段名一致,避免导出文件中的中文标题
 与查询页面的中文标题不一致.
***********************************************************
-->
<!ELEMENT resbundle (#PCDATA)>
<!ATTLIST resbundle path CDATA #REQUIRED>

<!--
***********************************************************
 指定导出文件的名称
***********************************************************
-->
<!ELEMENT outfilename (#PCDATA)>

<!--
***********************************************************
 指定VO的所有需要导出的字段,最少含有一个字段
***********************************************************
-->
<!ELEMENT fields (field+)>

<!--
***********************************************************
 指定需要导出的VO的单个字段,含有子元素definition,该子元素是可选的.
 
 name属性指定字段的名称(与VO里面定义一致),covertvalue属性指定该
 字段值在导出的时候是否需要进行转换,(譬如:套卡查询中,price字段导出
 的值为price/100),该属性的值只能是 字段名(+|-|*|/)数字的形式,若
 有特殊的实现,可以提供实现Excelout接口的实现类,实现接口的geValue
 方法.
***********************************************************
-->
<!ELEMENT field (definition*)>
<!ATTLIST field 
	name CDATA #REQUIRED
	covertvalue CDATA #IMPLIED
>

<!--
***********************************************************
 指定导出字段进行code2name翻译时用到的definition属性的值.
 该元素可包含字符数据或case子元素.
 
 若包含字符数据,则该字符数据为definition的值[该值有四种选择:
 系统参数($开头),配置方式(#开头),实现Code2name接口类的类short名,
 实现Excelout接口的类short名(以*开头)];
 
 若包含case子元素,则definition的值由case元素的内容决定,此时,
 definition元素应含有属性dependent,指定definition的值依赖于哪
 个字段(同一VO的字段)譬如:台帐查询中,typeid字段翻译所用到的definition的
 值依赖于sheetrestype字段的值不同而不同.
***********************************************************
-->
<!ELEMENT definition (#PCDATA|case)*>
<!ATTLIST definition dependent CDATA #IMPLIED>

<!--
***********************************************************
case元素内容指定definition的值,该值有四种选择:
 系统参数($开头),配置方式(#开头),实现Code2name接口类的类short名,
 实现Excelout接口类的类short名(以*开头).
 
 该元素含有属性oprtype,value,这些属性是必需的.
 oprtype属性指定依赖字段要进行的比较操作(只支持==,!=,>,<,>=,<=),
 value属性指定要进行比较操作的右操作符,依赖字段
 的值为左操作符.如台帐查询中,oprtype为"==",value为0时,
 表示如果sheetrestype==0为true时,则definition的值为该
 case元素的内容.
***********************************************************
-->
<!ELEMENT case (#PCDATA)>
<!ATTLIST case 
	oprtype CDATA #REQUIRED
	value CDATA #REQUIRED
>
<!--
end of excelout.dtd
-->

=== comahax/oldsnippet/PBOSS-REWARD/src/com/sunrise/boss/resource/excelout/excelout.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE excelout-config[
<!--
<!DOCTYPE excelout-config SYSTEM "excelout.dtd">
************************************************************
该dtd文件用于说明excelout.xml文件的配置方式

excelout-config为文档元素,含有最少一个entity子元素
************************************************************
-->
<!ELEMENT excelout-config (entity+)>

<!--
***********************************************************
 entity元素指定一个要导出数据的VO(对于多表查询的时候,因为有多个VO,所以
 需要使用复杂查询的方式,建立一个虚拟VO).
 entity元素的name属性是必须的,name的值应为VO的全类名,以保持唯一;
 exceloutbean属性指定用于导出操作的bean类全名,该类继承com.sunrise.boss.ui.resmanage.common.excelout.ExceloutBean类,
 若没有设置该属性,则程序中默认使用com.sunrise.boss.ui.resmanage.common.excelout.ExceloutBean类.
 showcount属性指定弹出页面中是否显示总记录数.
 
 entiy元素含有delegate,formname,resbundle,outfilename,fields子元素,
 除了delegate、cmmon、listvo元素外,其它的子元素必须要依声明的顺序存在.
***********************************************************
-->
<!ELEMENT entity (delegate*,command*,formname,listvo*,resbundle,outfilename,fields,headtitle*,endtitle*)>
<!ATTLIST entity 
			name ID #REQUIRED
			exceloutbean CDATA #IMPLIED
			showcount (yes|no) "no"
>

<!--
***********************************************************
 delegate元素指定调用其方法获得查询数据及其记录数的代理类,该元素不是必需
 的,如果在excelout.xml文件没有指定,则程序中会使用
 "com.sunrise.boss.delegate.common.CommonDelegate"作为元素内容;
 
 delegate元素含有query,count两属性,query属性指定delegate类中用以获得
 查询数据的查询方法的名称,如果没有指定该属性的值程序中默认使用"doQuery"作为方法名;
 count属性指定delegate类中用以获得符合导出条件的 记录总数的方法名称,
 如果没有指定该属性的值,程序中默认使用"doCount"作为方法名.
***********************************************************
-->
<!ELEMENT delegate (#PCDATA)>
<!ATTLIST delegate 
	query CDATA #IMPLIED
	count CDATA #IMPLIED
>
<!--
***********************************************************
 在生成导出文件时,若具体应用需要进行附加的特定操作时,可利用该元素值来区分
 特定的应用.譬如:台帐查询导出文件时,需要在文件末尾添加额外的输出字段,重载
 了afterWrite方法,该方法中利用common元素的值作为判断依据.
***********************************************************
-->
<!ELEMENT command (#PCDATA)>

<!--
***********************************************************
 元素formname指定进行查询操作的action对应的form类的全类名.
 该元素是必需的
***********************************************************
-->
<!ELEMENT formname (#PCDATA)>

<!--
***********************************************************
 元素listvo指定进行查询操作对应的listvo类的全类名.
 不指定则会根据VO类名生成符合目前编码规范的ListVO类名
***********************************************************
-->
<!ELEMENT listvo (#PCDATA)>

<!--
***********************************************************
 元素resbundle指定查询页面上显示的中文字段标题所对应的资源文件
  元素的内容为在resmanage-struts-config.xml文件中声明的message-resources
  元素的属性key的值;
  
 path属性指定资源文件的路径名.
 
 注意:页面上中文标题使用<bean:message bundle="key" key="fieldName"/>的方式
 即资源文件中,中文标题内容对应的key应与vo对应的字段名一致,避免导出文件中的中文标题
 与查询页面的中文标题不一致.
***********************************************************
-->
<!ELEMENT resbundle (#PCDATA)>
<!ATTLIST resbundle path CDATA #REQUIRED>

<!--
***********************************************************
 指定导出文件的名称
***********************************************************
-->
<!ELEMENT outfilename (#PCDATA)>

<!--
***********************************************************
 指定VO的所有需要导出的字段,最少含有一个字段
***********************************************************
-->
<!ELEMENT fields (field+)>

<!--
***********************************************************
 指定需要导出的VO的单个字段,含有子元素definition,该子元素是可选的.
 
 name属性指定字段的名称(与VO里面定义一致).
 
 covertvalue属性指定该字段值在导出的时候是否需要进行转换,(譬如:套卡查询中,price字段导出
 的值为price/100),该属性的值只能是 字段名(+|-|*|/)数字的形式,若
 有特殊的实现,可以提供实现Excelout接口的实现类,实现接口的geValue
 方法.
 var属性指定值转换时需要赋值的变量(多个变量用逗号分隔),如若covertvalue的值为'price/100+addjust+receivable',
 则var的值应为'addjust,receivable',字段price的值默认添加.
 
 format与formattype属性用于定义导出数据的格式,如数字、日期的格式。
***********************************************************
-->
<!ELEMENT field (definition*)>
<!ATTLIST field 
	name CDATA #REQUIRED
	covertvalue CDATA #IMPLIED
	var CDATA #IMPLIED
	format (none|STRING|NUMBER|DATE|CODE2NAME) "none"
	formattype CDATA #IMPLIED
>

<!--
***********************************************************
 指定导出字段进行code2name翻译时用到的definition属性的值.
 该元素可包含字符数据或case子元素.
 
 若包含字符数据,则该字符数据为definition的值[该值有四种选择:
 系统参数($开头),配置方式(#开头),实现Code2name接口类的类short名,
 实现Excelout接口的类short名(以*开头)];
 
 若包含case子元素,则definition的值由case元素的内容决定,此时,
 definition元素应含有属性dependent,指定definition的值依赖于哪
 个字段(同一VO的字段)譬如:台帐查询中,typeid字段翻译所用到的definition的
 值依赖于sheetrestype字段的值不同而不同.
***********************************************************
-->
<!ELEMENT definition (#PCDATA|case)*>
<!ATTLIST definition dependent CDATA #IMPLIED>

<!--
***********************************************************
case元素内容指定definition的值,该值有四种选择:
 系统参数($开头),配置方式(#开头),实现Code2name接口类的类short名,
 实现Excelout接口类的类short名(以*开头).
 
 该元素含有属性oprtype,value,这些属性是必需的.
 oprtype属性指定依赖字段要进行的比较操作(只支持==,!=,>,<,>=,<=),
 value属性指定要进行比较操作的右操作符,依赖字段
 的值为左操作符.如台帐查询中,oprtype为"==",value为0时,
 表示如果sheetrestype==0为true时,则definition的值为该
 case元素的内容.
***********************************************************
-->
<!ELEMENT case (#PCDATA)>
<!ATTLIST case 
	oprtype CDATA #REQUIRED
	value CDATA #REQUIRED
>

<!ELEMENT headtitle (#PCDATA)>

<!ELEMENT endtitle (#PCDATA)>
<!--
end of excelout.dtd
-->
]>

<excelout-config>

	<entity name="com.sunrise.boss.business.resmanage.reckoning.persistent.ReckoningVO">
		<delegate>com.sunrise.boss.delegate.resmanage.oprresmanage.reckon.ReckonDelegate</delegate>
		<command>reckon</command>
		<formname>com.sunrise.boss.ui.resmanage.oprresmanage.reckon.ReckonForm</formname>
		<resbundle path="/com/sunrise/boss/resource/i18n/resmanage/OprResManage_zh_CN.properties">oprresmanage</resbundle>
		<outfilename>服务厅台帐查询数据</outfilename>
		<fields>
			<field name="sheettime" format="DATE" formattype="yyyy-MM-dd HH:mm:ss"/>
			<field name="typeid">
				<definition dependent="sheetrestype">
					<case oprtype="==" value="0">$IM_SIMTYPE</case>
					<case oprtype="==" value="1">#VIPCARD</case>
					<case oprtype="==" value="2">#COMSYSTEM</case>
					<case oprtype="==" value="3">$IM_SIMTYPE</case>
				</definition>
			</field>
			<field name="sheetid"/>
			<field name="oprcode">
				<definition>ResOperator2Name</definition>
			</field>
			<field name="resaction">
				<definition>$IM_RESACTION</definition>
			</field>
			<field name="inamount"/>
			<field name="outamount"/>
			<field name="totalamount"/>
			<field name="memo"/>
		</fields>
	</entity>



	<entity name="com.sunrise.boss.business.resmanage.wayresstat.persistent.WayresstatVO" exceloutbean="com.sunrise.boss.ui.resmanage.oprresmanage.wayresstat.WayresstatExceloutbean">
		<command>wayresstat</command>
		<formname>com.sunrise.boss.ui.resmanage.oprresmanage.wayresstat.WayresstatForm</formname>
		<resbundle path="/com/sunrise/boss/resource/i18n/resmanage/OprResManage_zh_CN.properties">oprresmanage</resbundle>
		<outfilename>服务厅库存盘点统计数据</outfilename>
		<fields>
			<field name="statdate">
				<definition>TrantDate</definition>
			</field>
			<field name="wayid">
				<definition>#WAY</definition>
			</field>
			<field name="typeid">
				<definition dependent="sheetrestype">
					<case oprtype="==" value="0">$IM_SIMTYPE</case>
					<case oprtype="==" value="1">#VIPCARD</case>
					<case oprtype="==" value="2">#COMSYSTEM</case>
					<case oprtype="==" value="3">$IM_SIMTYPE</case>
				</definition>
			</field>
			<field name="amount"/>
			<field name="actualnum"/>
			<field name="diversitynum"/>
			<field name="memo"/>
		</fields>
	</entity>
	
	<entity name="com.sunrise.boss.business.resmanage.release.persistent.ReleaseVO">
		<formname>com.sunrise.boss.ui.resmanage.release.ReleaseForm</formname>
		<resbundle path="/com/sunrise/boss/resource/i18n/resmanage/Release_zh_CN.properties">release</resbundle>
		<outfilename>套卡销户处理结果查询</outfilename>
		<fields>
			<field name="oid"/>
			<field name="servnumber"/>
			<field name="intime"/>
			<field name="processed">
				<definition>#PROCESSED</definition>
			</field>
			<field name="processdate"/>
			<field name="operid"/>
			<field name="memo"/>
		</fields>
	</entity>
	
	<entity name="com.sunrise.boss.business.resmanage.noimsirela.persistent.NoimsirelaVO" >
		<delegate>com.sunrise.boss.delegate.resmanage.common.excelout.ExceloutDelegate</delegate>
		<formname>com.sunrise.boss.ui.resmanage.simcard.noimsirela.NoimsirelaForm</formname>
		<resbundle path="/com/sunrise/boss/resource/i18n/resmanage/Noimsirela_zh_CN.properties">noimsirela</resbundle>
		<outfilename>号码－SIM卡数据对应关系查询数据</outfilename>
		<fields>
			<field name="mobileno"/>
			<field name="imsino"/>
			<field name="starttime"/>
			<field name="stoptime" format="DATE" formattype="yyyy-MM-dd"/>
			<field name="oldmobileno"/>
			<field name="oldimsino"/>
			<field name="chgrsn"/>
		</fields>
	</entity>
	
	<entity name="com.sunrise.boss.business.resmanage.sim.persistent.SimVO">
		<delegate>com.sunrise.boss.delegate.resmanage.common.excelout.ExceloutDelegate</delegate>
		<formname>com.sunrise.boss.ui.resmanage.simcard.querysimcard.SimForm</formname>
		<resbundle path="/com/sunrise/boss/resource/i18n/resmanage/Sim_zh_CN.properties">Sim</resbundle>
		<outfilename>SIM卡查询数据</outfilename>
		<fields>
			<field name="iccid"/>
			<field name="cardmill">
				<definition>$IM_CARDMILL</definition>
			</field>
			<field name="pukno"/>
			<field name="begintime"/>
			<field name="stoptime"/>
			<field name="intime"/>
			<field name="wayid">
				<definition>#WAY</definition>
			</field>
			<field name="oprcode"/>
			<field name="simtype">
				<definition>$IM_SIMTYPE</definition>
			</field>
			<field name="usestate">
				<definition>$IM_SIMSTATUS</definition>
			</field>
			<field name="capacity"/>
			<field name="smscapacity"/>
			<field name="telcapacity"/>
		</fields>
	</entity>
	<entity name="com.sunrise.boss.business.resmanage.groupserial.persistent.GroupserialVO" showcount="no">
	<delegate>com.sunrise.boss.delegate.resmanage.common.excelout.ExceloutDelegate</delegate>
		<formname>com.sunrise.boss.ui.resmanage.groupserial.GroupserialForm</formname>
		<resbundle path="/com/sunrise/boss/resource/i18n/resmanage/Groupserial_zh_CN.properties">groupserial</resbundle>
